### ISSUE TITLE
Because of vcloud-login, instructions for running integration tests are now out of date

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-tools#205]
As a user of vCloud Tools I would like correct instructions on how to run the integration tests, and because of vcloud-login these are now out of date. As a developer on vCloud Tools I would like to avoid unnecessary duplication, so move this to the website and link from the READMEs.

See conversation [here](https://github.com/gds-operations/vcloud-core/pull/118).

[Pivotal story](https://www.pivotaltracker.com/story/show/78382670)

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
