### ISSUE TITLE
Install issue on Ubuntu 14.04

### ISSUE THREAD

**Issue by alanrenouf** [gds-operations/vcloud-tools#210]
Any idea why i get install issues please? 

root@ef512bcde1d0:/tmp# gem install vcloud-tools
Fetching: excon-0.44.2.gem (100%)
Fetching: formatador-0.2.5.gem (100%)
Fetching: mime-types-2.4.3.gem (100%)
Fetching: net-ssh-2.9.2.gem (100%)
Fetching: net-scp-1.2.1.gem (100%)
Fetching: fog-core-1.28.0.gem (100%)
Fetching: multi_json-1.10.1.gem (100%)
Fetching: fog-json-1.0.0.gem (100%)
Fetching: fog-xml-0.1.1.gem (100%)
Fetching: ipaddress-0.8.0.gem (100%)
Fetching: fog-aws-0.1.0.gem (100%)
Fetching: inflecto-0.0.2.gem (100%)
Fetching: fog-brightbox-0.7.1.gem (100%)
Fetching: fog-softlayer-0.4.1.gem (100%)
Fetching: fog-sakuracloud-1.0.0.gem (100%)
Fetching: fog-radosgw-0.0.3.gem (100%)
Fetching: fog-profitbricks-0.0.1.gem (100%)
Fetching: fog-voxel-0.0.2.gem (100%)
Fetching: CFPropertyList-2.3.0.gem (100%)
Fetching: fission-0.5.0.gem (100%)
Fetching: fog-vmfusion-0.0.1.gem (100%)
Fetching: fog-terremark-0.0.4.gem (100%)
Fetching: fog-ecloud-0.0.2.gem (100%)
Fetching: fog-storm_on_demand-0.1.0.gem (100%)
Fetching: fog-atmos-0.1.0.gem (100%)
Fetching: fog-serverlove-0.1.1.gem (100%)
Fetching: fog-1.27.0.gem (100%)
Fetching: mustache-0.99.8.gem (100%)
Fetching: vcloud-core-1.0.1.gem (100%)
Fetching: hashdiff-0.2.2.gem (100%)
Fetching: vcloud-edge_gateway-1.4.1.gem (100%)
Fetching: vcloud-launcher-1.0.0.gem (100%)
Fetching: vcloud-net_launcher-1.0.0.gem (100%)
Fetching: json-1.8.2.gem (100%)
Building native extensions.  This could take a while...
Fetching: vcloud-walker-4.0.0.gem (100%)
Fetching: vcloud-tools-1.0.0.gem (100%)
Successfully installed excon-0.44.2
Successfully installed formatador-0.2.5
Successfully installed mime-types-2.4.3
Successfully installed net-ssh-2.9.2
Successfully installed net-scp-1.2.1
Successfully installed fog-core-1.28.0
Successfully installed multi_json-1.10.1
Successfully installed fog-json-1.0.0
Successfully installed fog-xml-0.1.1
Successfully installed ipaddress-0.8.0
Successfully installed fog-aws-0.1.0
Successfully installed inflecto-0.0.2
Successfully installed fog-brightbox-0.7.1
Successfully installed fog-softlayer-0.4.1
Successfully installed fog-sakuracloud-1.0.0
Successfully installed fog-radosgw-0.0.3
Successfully installed fog-profitbricks-0.0.1
Successfully installed fog-voxel-0.0.2
Successfully installed CFPropertyList-2.3.0
Successfully installed fission-0.5.0
Successfully installed fog-vmfusion-0.0.1
Successfully installed fog-terremark-0.0.4
Successfully installed fog-ecloud-0.0.2
Successfully installed fog-storm_on_demand-0.1.0
Successfully installed fog-atmos-0.1.0
Successfully installed fog-serverlove-0.1.1
Successfully installed fog-1.27.0
Successfully installed mustache-0.99.8
Successfully installed vcloud-core-1.0.1
Successfully installed hashdiff-0.2.2
Successfully installed vcloud-edge_gateway-1.4.1
Successfully installed vcloud-launcher-1.0.0
Successfully installed vcloud-net_launcher-1.0.0
Successfully installed json-1.8.2
Successfully installed vcloud-walker-4.0.0
Successfully installed vcloud-tools-1.0.0
36 gems installed
Installing ri documentation for excon-0.44.2...
Installing ri documentation for formatador-0.2.5...
Installing ri documentation for mime-types-2.4.3...
unable to convert U+00D7 from UTF-8 to US-ASCII for lib/mime/types.rb, skipping
unable to convert U+00BD from UTF-8 to US-ASCII for lib/mime/types/loader.rb, skipping
unable to convert "\xE2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for Contributing.rdoc, skipping
unable to convert "\xC5" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for History.rdoc, skipping
unable to convert "\xE2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for Licence.rdoc, skipping
unable to convert "\xC5" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for README.rdoc, skipping
Installing ri documentation for net-ssh-2.9.2...
unable to convert "\xC5" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/net/ssh/authentication/agent/java_pageant.rb, skipping
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/net/ssh/authentication/pageant.rb, skipping
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/net/ssh/buffered_io.rb, skipping
unable to convert U+00F3 from UTF-8 to US-ASCII for lib/net/ssh/service/forward.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for LICENSE.txt, skipping
Installing ri documentation for net-scp-1.2.1...
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for LICENSE.txt, skipping
Installing ri documentation for fog-core-1.28.0...
Installing ri documentation for multi_json-1.10.1...
Installing ri documentation for fog-json-1.0.0...
Installing ri documentation for fog-xml-0.1.1...
Installing ri documentation for ipaddress-0.8.0...
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for README.rdoc, skipping
Installing ri documentation for fog-aws-0.1.0...
unable to convert "\xE2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/aws/requests/glacier/list_vaults.rb, skipping
Installing ri documentation for inflecto-0.0.2...
Installing ri documentation for fog-brightbox-0.7.1...
Installing ri documentation for fog-softlayer-0.4.1...
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/dns/update_record.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/dns/get_domain.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/dns/delete_record.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/dns/create_record.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/dns/get_record.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/dns/create_domain.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/dns/delete_domain.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/dns/get_records.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/dns/get_domains.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/dns/get_domain_by_name.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_portable_subnet_package_id.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/delete_network.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_subnet_package_id.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/create_subnet.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_datacenters.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_global_ip_records.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/list_networks.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/delete_network_tags.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_global_ip_address.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/create_network_tags.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/unroute_global_ip.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_subnet_price_code.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_network.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/delete_global_ip_address.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_network_tags.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/route_global_ip.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_public_vlan_price_code.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_ip_address.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_ip_addresses.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_references_by_tag_name.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_subnet.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_private_vlan_price_code.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/create_network.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_datacenter_routers.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/list_subnets.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/network/get_portable_subnet_price_code.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/describe_tags.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/delete_bare_metal_tags.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/create_key_pair.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/reboot_vm.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/create_vm_tags.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/reboot_bare_metal_server.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/power_off_vm.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/update_key_pair.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/get_vms.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/power_on_bare_metal_server.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/delete_vm.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/power_off_bare_metal_server.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/get_bare_metal_server.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/get_vm.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/get_tag.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/delete_key_pair.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/delete_bare_metal_server.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/create_bare_metal_server.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/get_key_pairs.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/create_vm.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/get_references_by_tag_name.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/get_vm_tags.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/create_vms.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/get_bare_metal_tags.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/get_key_pair.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/get_bare_metal_servers.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/create_bare_metal_tags.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/power_on_vm.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/compute/delete_vm_tags.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/product/get_packages.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/product/get_package_items.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/requests/product/get_package_item.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/compute.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/dns/records.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/dns/domain.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/dns/domains.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/dns/record.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/network/tags.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/network/networks.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/network/network.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/network/datacenter.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/network/subnet.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/network/tag.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/network/ip.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/network/datacenters.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/network/ips.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/network/subnets.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/storage/files.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/storage/directories.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/storage/directory.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/storage/file.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/compute/tags.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/compute/images.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/compute/servers.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/compute/key_pair.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/compute/network_component.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/compute/image.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/compute/flavor.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/compute/tag.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/compute/flavors.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/compute/network_components.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/compute/server.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/compute/key_pairs.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/product/item.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/product/package.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/product/packages.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/models/product/items.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/network.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/core.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/version.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/storage.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/dns.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/product.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer/compute/shared.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/softlayer.rb, skipping
Installing ri documentation for fog-sakuracloud-1.0.0...
unable to convert U+30D7 from UTF-8 to US-ASCII for lib/fog/sakuracloud/requests/volume/list_plans.rb, skipping
unable to convert U+57FA from UTF-8 to US-ASCII for lib/fog/sakuracloud/requests/volume/list_archives.rb, skipping
unable to convert U+30D7 from UTF-8 to US-ASCII for lib/fog/sakuracloud/requests/compute/list_plans.rb, skipping
unable to convert U+77F3 from UTF-8 to US-ASCII for lib/fog/sakuracloud/requests/compute/list_zones.rb, skipping
Installing ri documentation for fog-radosgw-0.0.3...
Installing ri documentation for fog-profitbricks-0.0.1...
Installing ri documentation for fog-voxel-0.0.2...
Installing ri documentation for CFPropertyList-2.3.0...
unable to convert U+2026 from UTF-8 to US-ASCII for lib/cfpropertylist/rbCFPropertyList.rb, skipping
unable to convert U+201E from UTF-8 to US-ASCII for lib/cfpropertylist/rbBinaryCFPropertyList.rb, skipping
unable to convert "\xE2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for README, skipping
Installing ri documentation for fission-0.5.0...
Installing ri documentation for fog-vmfusion-0.0.1...
Installing ri documentation for fog-terremark-0.0.4...
Installing ri documentation for fog-ecloud-0.0.2...
Installing ri documentation for fog-storm_on_demand-0.1.0...
Installing ri documentation for fog-atmos-0.1.0...
Installing ri documentation for fog-serverlove-0.1.1...
Installing ri documentation for fog-1.27.0...
unable to convert "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/tasks/changelog_task.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/vcloud_director/requests/compute/post_power_on_vapp.rb, skipping
unable to convert "\xC2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/bin/softlayer.rb, skipping
unable to convert U+00E5 from UTF-8 to US-ASCII for lib/fog/rackspace/models/compute_v2/server.rb, skipping
unable to convert "\xE2" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to US-ASCII for lib/fog/fogdocker/requests/compute/container_all.rb, skipping

RDoc::Parser::Ruby failure around line 40 of
lib/fog/xenserver/requests/compute/create_sr.rb

Before reporting this, could you check that the file you're documenting
has proper syntax:

  /usr/bin/ruby1.9.1 -c lib/fog/xenserver/requests/compute/create_sr.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(RDoc::Error) unknown type of %string "i"

ERROR:  While generating documentation for fog-1.27.0
... MESSAGE:   unknown type of %string "i"
... RDOC args: --ri --op /var/lib/gems/1.9.1/doc/fog-1.27.0/ri --charset=UTF-8 lib README.md --title fog-1.27.0 Documentation --quiet
root@ef512bcde1d0:/tmp#

**Comment by rjw1** [comment]
The gems actually installed fine
> 36 gems installed

There were doc generation issues in [fog](https://github.com/fog/fog) which should probably be reported to them
