### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by noels** [gds-operations/vcloud-tools#215]
I tried to install vcloud-tools on a new install of OSX 10.10.5 with the following command:

sudo gem install vcloud-tools

I got this response:

ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: vcloud-tools requires vcloud-core (>= 0); vcloud-walker requires vcloud-core (~> 1.0.0); vcloud-net_launcher requires vcloud-core (~> 1.1.0); vcloud-launcher requires vcloud-core (~> 1.1.0); vcloud-edge_gateway requires vcloud-core (~> 1.0.0)

I expected the command to complete without error.

I then installed each component separately with:

sudo gem install vcloud-core
sudo gem install vcloud-walker etc.

The tools are working correctly after being individually installed.

**Comment by deanwilson** [comment]
Thank you for raising this issue. We will soon be releasing a version 2.0 of the related projects and this issue will hopefully be corrected then. Apologies for any issues it caused.
