### ISSUE TITLE
vcloud-login returns extra carriage return character

### ISSUE THREAD

**Issue by jambo2kuk** [gds-operations/vcloud-tools#217]
vcloud-login 1.1.0 returns an additional carriage return before the export command, this causes issues when scripted.

cannot find command /rexport

**Comment by mattbostock** [comment]
Thanks @jambo2kuk. We've had other reports of this and indeed I've seen it myself. The workaround for now is to avoid the `eval`, e.g.:

```
FOG_CREDENTIAL=xyz vcloud-login
```

You should take care however if copying and pasting the resulting `export` line to avoid it being saved in your shell history - in Bash you can insert a space before the line to prevent it from being saved to your Bash history, for example.

We'll look into this as soon as we can.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.

Hopefully the work around shown by @mattbostock is sufficient for your usage.
